package paths

const (
	GlobalDir =   "C:/interna-dokumentacia-backend/backend/"
	//"./"
	Scripts = "/scripts/"
)

const (
	Login                 = "/auth/login"
	Logout                = "/auth/logout"
	Kiosk                 = "/auth/kiosk"
	AllEmployees          = "/employees/all"
	ByIdsEmployees        = "/employees/ids"
	FilterEmployees       = "/employees"
	Upload                = "/file/upload"
	Export                = "/file/export"
	Combinations          = "/combinations"
	Branches              = "/branches"
	Cities                = "/cities"
	Departments           = "/departments"
	Divisions             = "/divisions"
	DocumentAdd           = "/document/create"
	DocumentCreateConfirm = "/document/create/confirm"
	DocumentUpdate        = "/document/update"
	DocumentConfirm       = "/document/confirm"
	DocumentUpdateConfirm = "/document/update/confirm"
	DocumentActual        = "/document/actual"
	DocumentEdited        = "/document/edited"
	DocumentFilter        = "/document/filter"
	DocumentReport        = "/document/report"
	DocumentManager       = "/document/manager"
	UnsignedSigns         = "/unsigned/signatures"
	SkillMatrix           = "/skill/matrix"
	SignDocument          = "/sign/document"
	SignSuperior          = "/sign/superior"
	SignTraining          = "/sign/training"
	SignedSigns           = "/signed/signatures"
	AllLanguages          = "/languages/all"
	Language              = "/language"
	TrainingUpdateConfirm = "/training/update/confirm"
	TrainingConfirm       = "/training/confirm"
	TrainingSave          = "/training/create"
	TrainingSaveConfirm   = "/training/create/confirm"
	TrainingUpdate        = "/training/update"
	Resigns               = "/resigns"
	Cancels               = "/cancels"
	EditedTraining        = "/training/edited"
	TrainingAll           = "/training/all"
	TrainingFilter        = "/training/filter"
	TrainingReport        = "/training/report"
	LectorsAll            = "/lectors/all"
	Control               = "/control7777777"
	HomePage              = "/homePageBackend"
)
